function [car] = createNewCar(stats, img)
%returns an initial car struct
    car =struct (...
                'id',0 ,...
                'Age', 1 ,...
                'invisbiltyCount', 0,...
                'Centroids', stats.Centroid,...
                'Orientation',stats.Orientation,...
                'histogram', normalizedHistogram(img),...
                'crossed', 0....
                );
    end