function [Cars] = initCars()
    Cars = struct (...
                'id',{} ,...
                'Age', {} ,...
                'invisbiltyCount', {},...
                'Centroids', {},...
                'Orientation',{},...
                'histogram', {},...
                'crossed', {}...
                );